
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEnonassocUMINUSleftEXPONENTDIVIDE EQUALS EXPONENT IDENTIFIER LPAREN MINUS NUMBER PLUS RPAREN TIMES\n    statement : assignment\n              | expression\n    assignment : IDENTIFIER EQUALS expressionexpression12 : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : MINUS expression %prec UMINUSexpression : LPAREN expression RPARENexpression : NUMBERexpression : expression EXPONENT expressionexpression : IDENTIFIER'
    
_lr_action_items = {'IDENTIFIER':([0,5,6,8,9,],[4,11,11,11,11,]),'MINUS':([0,5,6,8,9,],[5,5,5,5,5,]),'LPAREN':([0,5,6,8,9,],[6,6,6,6,6,]),'NUMBER':([0,5,6,8,9,],[7,7,7,7,7,]),'$end':([1,2,3,4,7,10,11,13,14,15,],[0,-1,-2,-12,-10,-8,-12,-11,-3,-9,]),'EXPONENT':([3,4,7,10,11,12,13,14,15,],[8,-12,-10,8,-12,8,-11,8,-9,]),'EQUALS':([4,],[9,]),'RPAREN':([7,10,11,12,13,15,],[-10,-8,-12,15,-11,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'assignment':([0,],[2,]),'expression':([0,5,6,8,9,],[3,10,12,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> assignment','statement',1,'p_statement','yacc_grammar.py',29),
  ('statement -> expression','statement',1,'p_statement','yacc_grammar.py',30),
  ('assignment -> IDENTIFIER EQUALS expression','assignment',3,'p_assignment','yacc_grammar.py',36),
  ('expression12 -> expression PLUS expression','expression12',3,'p_expression_binop','yacc_grammar.py',45),
  ('expression12 -> expression MINUS expression','expression12',3,'p_expression_binop','yacc_grammar.py',46),
  ('expression12 -> expression TIMES expression','expression12',3,'p_expression_binop','yacc_grammar.py',47),
  ('expression12 -> expression DIVIDE expression','expression12',3,'p_expression_binop','yacc_grammar.py',48),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','yacc_grammar.py',60),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','yacc_grammar.py',65),
  ('expression -> NUMBER','expression',1,'p_expression_number','yacc_grammar.py',70),
  ('expression -> expression EXPONENT expression','expression',3,'p_expression_exponent','yacc_grammar.py',75),
  ('expression -> IDENTIFIER','expression',1,'p_expression_var','yacc_grammar.py',89),
]
